[package]
name    = "swift_vec"
version = "0.1.0"
edition = "2021"
exclude = [
    ".github/*",
    ".vscode/*",
    "tests/*",
]

description = "A convenient and comfortable vector maths crate that supports 2D, 3D, and 4D vectors - along with additional scalar math."
license     = "MIT OR Apache-2.0"

[dependencies]
num-traits = "0.2.17"
approx     = "0.5.1"